/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as BreakRouteImport } from './routes/break'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ManifestRouteImport } from './routes/manifest'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as ParcelsRouteImport } from './routes/parcels'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SummaryRouteImport } from './routes/summary'
import { Route as HelpSeqRouteImport } from './routes/help_.$seq'
import { Route as HistoryIdRouteImport } from './routes/history_.$id'
import { Route as NavSeqRouteImport } from './routes/nav.$seq'
import { Route as ProfileEditRouteImport } from './routes/profile_.edit'
import { Route as ScanSeqRouteImport } from './routes/scan.$seq'
import { Route as StopSeqRouteImport } from './routes/stop.$seq'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BreakRoute = BreakRouteImport.update({
  id: '/break',
  path: '/break',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestRoute = ManifestRouteImport.update({
  id: '/manifest',
  path: '/manifest',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const ParcelsRoute = ParcelsRouteImport.update({
  id: '/parcels',
  path: '/parcels',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpSeqRoute = HelpSeqRouteImport.update({
  id: '/help_/$seq',
  path: '/help/$seq',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIdRoute = HistoryIdRouteImport.update({
  id: '/history_/$id',
  path: '/history/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NavSeqRoute = NavSeqRouteImport.update({
  id: '/nav/$seq',
  path: '/nav/$seq',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile_/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanSeqRoute = ScanSeqRouteImport.update({
  id: '/scan/$seq',
  path: '/scan/$seq',
  getParentRoute: () => rootRouteImport,
} as any)
const StopSeqRoute = StopSeqRouteImport.update({
  id: '/stop/$seq',
  path: '/stop/$seq',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/break': typeof BreakRoute
  '/history': typeof HistoryRoute
  '/manifest': typeof ManifestRoute
  '/metrics': typeof MetricsRoute
  '/notifications': typeof NotificationsRoute
  '/offline': typeof OfflineRoute
  '/parcels': typeof ParcelsRoute
  '/performance': typeof PerformanceRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/summary': typeof SummaryRoute
  '/help/$seq': typeof HelpSeqRoute
  '/history/$id': typeof HistoryIdRoute
  '/nav/$seq': typeof NavSeqRoute
  '/profile/edit': typeof ProfileEditRoute
  '/scan/$seq': typeof ScanSeqRoute
  '/stop/$seq': typeof StopSeqRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/break': typeof BreakRoute
  '/history': typeof HistoryRoute
  '/manifest': typeof ManifestRoute
  '/metrics': typeof MetricsRoute
  '/notifications': typeof NotificationsRoute
  '/offline': typeof OfflineRoute
  '/parcels': typeof ParcelsRoute
  '/performance': typeof PerformanceRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/summary': typeof SummaryRoute
  '/help/$seq': typeof HelpSeqRoute
  '/history/$id': typeof HistoryIdRoute
  '/nav/$seq': typeof NavSeqRoute
  '/profile/edit': typeof ProfileEditRoute
  '/scan/$seq': typeof ScanSeqRoute
  '/stop/$seq': typeof StopSeqRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/break': typeof BreakRoute
  '/history': typeof HistoryRoute
  '/manifest': typeof ManifestRoute
  '/metrics': typeof MetricsRoute
  '/notifications': typeof NotificationsRoute
  '/offline': typeof OfflineRoute
  '/parcels': typeof ParcelsRoute
  '/performance': typeof PerformanceRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/summary': typeof SummaryRoute
  '/help_/$seq': typeof HelpSeqRoute
  '/history_/$id': typeof HistoryIdRoute
  '/nav/$seq': typeof NavSeqRoute
  '/profile_/edit': typeof ProfileEditRoute
  '/scan/$seq': typeof ScanSeqRoute
  '/stop/$seq': typeof StopSeqRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/break'
    | '/history'
    | '/manifest'
    | '/metrics'
    | '/notifications'
    | '/offline'
    | '/parcels'
    | '/performance'
    | '/profile'
    | '/settings'
    | '/summary'
    | '/help/$seq'
    | '/history/$id'
    | '/nav/$seq'
    | '/profile/edit'
    | '/scan/$seq'
    | '/stop/$seq'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/break'
    | '/history'
    | '/manifest'
    | '/metrics'
    | '/notifications'
    | '/offline'
    | '/parcels'
    | '/performance'
    | '/profile'
    | '/settings'
    | '/summary'
    | '/help/$seq'
    | '/history/$id'
    | '/nav/$seq'
    | '/profile/edit'
    | '/scan/$seq'
    | '/stop/$seq'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/break'
    | '/history'
    | '/manifest'
    | '/metrics'
    | '/notifications'
    | '/offline'
    | '/parcels'
    | '/performance'
    | '/profile'
    | '/settings'
    | '/summary'
    | '/help_/$seq'
    | '/history_/$id'
    | '/nav/$seq'
    | '/profile_/edit'
    | '/scan/$seq'
    | '/stop/$seq'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  BreakRoute: typeof BreakRoute
  HistoryRoute: typeof HistoryRoute
  ManifestRoute: typeof ManifestRoute
  MetricsRoute: typeof MetricsRoute
  NotificationsRoute: typeof NotificationsRoute
  OfflineRoute: typeof OfflineRoute
  ParcelsRoute: typeof ParcelsRoute
  PerformanceRoute: typeof PerformanceRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  SummaryRoute: typeof SummaryRoute
  HelpSeqRoute: typeof HelpSeqRoute
  HistoryIdRoute: typeof HistoryIdRoute
  NavSeqRoute: typeof NavSeqRoute
  ProfileEditRoute: typeof ProfileEditRoute
  ScanSeqRoute: typeof ScanSeqRoute
  StopSeqRoute: typeof StopSeqRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/break': {
      id: '/break'
      path: '/break'
      fullPath: '/break'
      preLoaderRoute: typeof BreakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest': {
      id: '/manifest'
      path: '/manifest'
      fullPath: '/manifest'
      preLoaderRoute: typeof ManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parcels': {
      id: '/parcels'
      path: '/parcels'
      fullPath: '/parcels'
      preLoaderRoute: typeof ParcelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help_/$seq': {
      id: '/help_/$seq'
      path: '/help/$seq'
      fullPath: '/help/$seq'
      preLoaderRoute: typeof HelpSeqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history_/$id': {
      id: '/history_/$id'
      path: '/history/$id'
      fullPath: '/history/$id'
      preLoaderRoute: typeof HistoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nav/$seq': {
      id: '/nav/$seq'
      path: '/nav/$seq'
      fullPath: '/nav/$seq'
      preLoaderRoute: typeof NavSeqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/edit': {
      id: '/profile_/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/$seq': {
      id: '/scan/$seq'
      path: '/scan/$seq'
      fullPath: '/scan/$seq'
      preLoaderRoute: typeof ScanSeqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stop/$seq': {
      id: '/stop/$seq'
      path: '/stop/$seq'
      fullPath: '/stop/$seq'
      preLoaderRoute: typeof StopSeqRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  BreakRoute: BreakRoute,
  HistoryRoute: HistoryRoute,
  ManifestRoute: ManifestRoute,
  MetricsRoute: MetricsRoute,
  NotificationsRoute: NotificationsRoute,
  OfflineRoute: OfflineRoute,
  ParcelsRoute: ParcelsRoute,
  PerformanceRoute: PerformanceRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  SummaryRoute: SummaryRoute,
  HelpSeqRoute: HelpSeqRoute,
  HistoryIdRoute: HistoryIdRoute,
  NavSeqRoute: NavSeqRoute,
  ProfileEditRoute: ProfileEditRoute,
  ScanSeqRoute: ScanSeqRoute,
  StopSeqRoute: StopSeqRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
